before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/discord-notify-ip-change/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
dockers:
  - image_templates:
      - ghcr.io/dustinspecker/discord-notify-ip-change:{{ .Version }}-amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - ghcr.io/dustinspecker/discord-notify-ip-change:{{ .Version }}-arm64v8
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: "ghcr.io/dustinspecker/discord-notify-ip-change:{{ .Version }}"
    image_templates:
      - ghcr.io/dustinspecker/discord-notify-ip-change:{{ .Version }}-amd64
      - ghcr.io/dustinspecker/discord-notify-ip-change:{{ .Version }}-arm64v8
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
